name: Workflow at scale

on:

  workflow_dispatch:

jobs:

  caller:

    strategy:
      matrix:
        consumers: ['batch0', 'batch1', 'batch2', 'batch3', 'batch4', 'batch5', 'batch6', 'batch7', 'batch8', 'batch9', 'batch10', 'batch11', 'batch12', 'batch13', 'batch14', 'batch15', 'batch16', 'batch17', 'batch18', 'batch19']

    uses: nimadini/called/.github/workflows/workflow_at_scale.yml@main
