name: Caller workflow (matrix)

on:
  push:

  workflow_dispatch:

jobs:

  strategy:
    matrix:
      consumers: [foo, bar]

  caller:
    uses: nimadini/called/.github/workflows/workflow_with_matrix.yml@main
