name: Caller workflow (matrix)

on:
  push:

  workflow_dispatch:

jobs:

  caller:

    strategy:
      matrix:
        consumers: [foo, bar]

    uses: nimadini/called/.github/workflows/workflow_with_matrix.yml@main
